# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
  # R specific hooks
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3.9133
    hooks:
      - id: style-files
        args: [--style_pkg=styler, --style_fun=tidyverse_style]
      - id: roxygenize
      - id: use-tidy-description
      - id: spell-check
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.png|
          .*\.RData|
          .*\.rds|
          .*\.Rds|
          .*\.Rproj|
          .*\.svg|
          \.gitignore|
          \.pre-commit-.*|
          \.Rbuildignore|
          \.Renviron|
          \.Rprofile|
          data/.*|
          NAMESPACE|
          WORDLIST
          )$
      - id: lintr
      - id: readme-rmd-rendered
      - id: parsable-R
      - id: no-browser-statement
      - id: deps-in-desc

  # Don't commit R artifacts
  - repo: local
    hooks:
      - id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.
