name: Autopdate hooks

on:
  schedule:
    - cron: 0 5 1,15 * *
  push:
    branches: [main, master]

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Autoupdate hooks
        run: .github/workflows/autoupdate.sh

      - name: Commit and push changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add examples/
          git commit -m "Autoupdate hooks" || echo "No changes to commit"
          git push origin
